FROM alpine:3

ENV SHELL=/bin/bash

COPY ../dotfiles/* /root/
RUN  set -ex \
      && apk add --no-cache --update \
      # Basic shell stuff
      bash \
      bash-completion \
      readline \
      grep \
      gawk \
      tree \
      # Interacting with the networks
      curl \
      wget \
      jq \
      drill \
      nmap \
      netcat-openbsd \
      socat \
      mtr \
      bind-tools \
      openssl \
      # Monitoring / Shell tools
      htop \
      mc \
      # Development tools
      vim \
      tmux \
      git \
      tig \
      # Scripting languages
      python3 \
  && rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*


CMD ["bash"]
