FROM jeanblanchard/alpine-glibc:latest

ENV SHELL=/bin/bash

RUN  set -ex \
      && apk add --no-cache --update \
      # Basic shell stuff
      bash \
      bash-completion \
      readline \
      grep \
      gawk \
      tree \
      augeas \
      shadow \
      # Interacting with the networks
      curl \
      wget \
      jq \
      drill \
      nmap \
      netcat-openbsd \
      socat \
      mtr \
      bind-tools \
      openssl \
      openssh-client \
      openssh-server \
      # Monitoring / Shell tools
      htop \
      mc \
      # Development tools
      vim \
      tmux \
      git \
      tig \
      # Scripting languages
      python3 \
  && mkdir -p /etc/bash_completion.d \
  && touch /etc/bashrc \
  && deluser $(getent passwd 33 | cut -d: -f1) \
  && delgroup $(getent group 33 | cut -d: -f1) 2>/dev/null || true \
  && mkdir -p ~root/.ssh /etc/authorized_keys && chmod 700 ~root/.ssh/ \
  && augtool 'set /files/etc/ssh/sshd_config/AuthorizedKeysFile ".ssh/authorized_keys /etc/authorized_keys/%u"' \
  && echo -e "Port 22\n" >> /etc/ssh/sshd_config \
  && cp -a /etc/ssh /etc/ssh.cache \
  && rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*

ENV KUSTOMIZE_VERSION=4.5.2
ENV K9S_VERSION=0.25.18
ENV SOPS_VERSION=3.7.1

RUN  set -ex \
    && apk add --no-cache --update \
        docker-cli \
    && curl -L -o /usr/bin/kubectl \
    "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x /usr/bin/kubectl \
    && kubectl completion bash > /etc/bash_completion.d/kubectl \
    && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash \
    && helm completion bash > /etc/bash_completion.d/helm \
    && curl -L -o kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz \
    && tar xzf kustomize.tar.gz \
    && mv kustomize /usr/bin \
    && rm -f kustomize.tar.gz \
    && kustomize completion bash > /etc/bash_completion.d/kustomize \
    && curl -L -o k9s.tar.gz https://github.com/derailed/k9s/releases/download/v${K9S_VERSION}/k9s_Linux_x86_64.tar.gz \
    && tar xzf k9s.tar.gz \
    && mv k9s /usr/bin \
    && rm -f k9s.tar.gz \
    && curl -L -o sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux \
    && chmod +x sops \
    && mv sops /usr/bin \
    && rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*

ENV TERRAFORM_VERSION=1.1.6

RUN  set -ex \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip \
    && curl -L -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip -d /usr/bin terraform.zip \ 
    && rm -rf terraform.zip \
    && mkdir -p /root/.aws \
    && touch /root/.aws/credentials \
    && touch /root/.aws/config

COPY dotfiles/* /root/
COPY app /app

RUN  set -ex \
    && echo 'source ~/.iac_completion' >> /root/.bashrc \
    && chmod +x /app/*

CMD ["bash"]