name: CI-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: abriko
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build iamge
        run: |
          docker build -t abriko/toolkit:latest .
          docker push abriko/toolkit:latest
